services:
  undb:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: undb
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3721:3721
    environment:
      - UNDB_DB_TURSO_URL=http://db:8080
      - UNDB_MINIO_STORAGE_ENDPOINT=http://minio:9000
    depends_on:
      - db
      - minio
