previewsEnabled: true
services:
  # A Docker web service
  - type: web
    name: egodb
    env: docker
    repo: https://github.com/ego-io/egodb.git
    region: singapore
    plan: starter
    branch: develop
    rootDir: .
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: EGODB_ADMIN_EMAIL
        value: test@example.com
      - key: EGODB_ADMIN_PASSWORD
        value: 123456

    domains:
      - demo.egodb.io
